apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraindster-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraindster-frontend
  template:
    metadata:
      labels:
        app: fraindster-frontend
    spec:
      containers:
      - name: frontend
        image: fraindster-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: fraindster-config
              key: api-url 